#Diccionario de categorias/extensiones

organizacion = {
    # Imagenes
    ".png": "imagenes",
    ".jpg": "imagenes",
    ".jpeg": "imagenes",
    ".gif": "imagenes",
    ".bmp": "imagenes",
    ".tiff": "imagenes",
    ".svg": "imagenes",
    ".ico": "imagenes",
    ".drawio": "imagenes",
    ".webp": "imagenes",
    ".psd": "imagenes",
    ".heic": "imagenes",

    # Codigos
    ".java": "codigos",
    ".py": "codigos",
    ".c": "codigos",
    ".cu": "codigos",
    ".cpp": "codigos",
    ".js": "codigos",
    ".ts": "codigos",
    ".html": "codigos",
    ".css": "codigos",
    ".php": "codigos",
    ".rb": "codigos",
    ".go": "codigos",
    ".rs": "codigos",
    ".swift": "codigos",
    ".kt": "codigos",
    ".cs": "codigos",
    ".sh": "codigos",
    ".bat": "codigos",
    ".pl": "codigos",
    ".sql": "codigos",
    ".json": "codigos",
    ".xml": "codigos",
    ".yml": "codigos",
    ".yaml": "codigos",

    # Instaladores
    ".msi": "instaladores",
    ".exe": "instaladores",
    ".apk": "instaladores",
    ".deb": "instaladores",
    ".rpm": "instaladores",
    ".pkg": "instaladores",
    ".dmg": "instaladores",

    # Audios
    ".mp3": "audios",
    ".flac": "audios",
    ".wav": "audios",
    ".aac": "audios",
    ".ogg": "audios",
    ".m4a": "audios",
    ".wma": "audios",

    # Videos
    ".mp4": "videos",
    ".mkv": "videos",
    ".avi": "videos",
    ".mov": "videos",
    ".wmv": "videos",
    ".flv": "videos",
    ".webm": "videos",
    ".mpeg": "videos",

    # Documentos
    ".doc": "documentos",
    ".docx": "documentos",
    ".odt": "documentos",
    ".xls": "documentos",
    ".xlsx": "documentos",
    ".ods": "documentos",
    ".ppt": "documentos",
    ".pptx": "documentos",
    ".odp": "documentos",
    ".pdf": "documentos",
    ".txt": "documentos",
    ".md": "documentos",
    ".rtf": "documentos",
    ".tex": "documentos",
    ".csv": "documentos",

    # Comprimidos
    ".zip": "comprimidos",
    ".rar": "comprimidos",
    ".7z": "comprimidos",
    ".tar": "comprimidos",
    ".gz": "comprimidos",
    ".bz2": "comprimidos",
    ".xz": "comprimidos",
    ".iso": "comprimidos",

    # Otros
    ".lnk": "accesos_directos",
    ".ini": "configuracion",
    ".log": "logs",
    ".": "otros",
}